# Generated by Django 5.1.1 on 2024-10-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreactapp', '0009_alter_cartitem_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='extra_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
