# Generated by Django 5.1.1 on 2024-10-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreactapp', '0012_order_created_at_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='picture',
            field=models.CharField(default='http://example.com/default-image.jpg', max_length=255),
        ),
    ]
