# Generated by Django 5.1.1 on 2024-11-05 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myreactapp', '0019_order_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
    ]
