# Generated by Django 5.1.1 on 2024-09-09 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myreactapp', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
