# Generated by Django 5.1.1 on 2024-09-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myreactapp', '0003_remove_cartitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
