# Generated by Django 5.1.1 on 2024-09-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreactapp', '0006_cart_is_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='myreactapp.ingredients'),
        ),
    ]
