# Generated by Django 5.1.1 on 2024-10-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreactapp', '0007_ingredients_dish_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='myreactapp.ingredients'),
        ),
    ]
