# Generated by Django 5.1.1 on 2024-10-06 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreactapp', '0008_cartitem_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='myreactapp.dish'),
        ),
    ]
