# Generated by Django 5.1.1 on 2024-10-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreactapp', '0013_dish_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
