# Generated by Django 5.1.1 on 2024-10-24 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myreactapp', '0014_cartitem_custom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='custom_name',
        ),
    ]
