# Generated by Django 5.1.1 on 2024-10-25 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreactapp', '0015_remove_cartitem_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myreactapp.menu'),
        ),
    ]
