# Generated by Django 5.1.1 on 2024-10-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreactapp', '0016_cartitem_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_dish_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
