# Generated by Django 5.1.1 on 2024-11-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myreactapp', '0017_cartitem_custom_dish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_dish_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
